version: '3'

services:
  ssti:
    build: 
      context: ./ssti
    ports:
      - 8888:8888
    restart: always
  file-upload:
    build: ./file-upload
    ports:
      - 8000:8000
    restart: always
    volumes:
      - file-upload/src:/var/www/html
  sqli:
    build:
      context: ./sqli
      ports:
      - 8001:80
    restart: always
    volumes:
      - sqli/src:/var/www/html